### ISSUE TITLE
on 2020.11.14 task

### ISSUE THREAD

**Issue by agricolamz** [dasharakelova/abaza_analyzer#1]
* The form for 1000 is *зкьы* and not *зыкь*. Or you want to solve it with phonology?
* Ah-ah-ah... everything is so complicated. We need to discuss phonology first...

**Comment by nlhowell** [comment]
We should be in much better shape; please pull:

The following changes since commit 1287f515d845f290538e4071353fb568d4042c99:

  tests fixed (2020-12-12 17:14:18 +0300)

are available in the Git repository at:

  https://gitlab.com/nlhowell/abq.git

for you to fetch changes up to 97a2436ed0b5510ff18fdf816964963f1b63088f:

  add sourced tests from garik (2020-12-17 13:32:50 +0300)

----------------------------------------------------------------
Nick Howell (15):
      remove \r everywhere :/
      ignore test products
      add stress and related phonology
      twol: correct encoding of palochka
      twol: у is sometimes a consonant
      twol: з acts as a sonorant, see Arkadiev section 2.3
      twol: clearer vowel hiatus resolution
      twol: add CSC resolution, see Arkadiev 2.3
      twol: per-syllable stress, not per-vowel
      lexd: correct hundreds variant for 100
      lexd: all numbers <=10 are now recessive
      lexd: remove dominant ы from <iter>
      lexd: add AC annotation to <link>:ы
      compare: bail out gracefully tests is empty
      add sourced tests from garik

 .gitignore             |   4 +++
 Makefile               |  18 ++++++++++--
 compare.sh             |   6 ++--
 drop-accent.twol       |   6 ++++
 garik.csv              |  65 +++++++++++++++++++++++++++++++++++++++++++
 numerals.txt           | 150 +++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------
 numerals_isolated.lexd | 158 +++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------
 numerals_isolated.twol |  74 +++++++++++++++++++++++++++++++++++++++++--------
 pairtest.txt.res       |  62 -----------------------------------------
 9 files changed, 313 insertions(+), 230 deletions(-)
 create mode 100644 drop-accent.twol
 create mode 100644 garik.csv
 delete mode 100644 pairtest.txt.res

**Comment by nlhowell** [comment]
Can we close this?
